version: 2.1
orbs:
  node: circleci/node@4
  codecov: codecov/codecov@1
jobs:
  test:
    docker:
      - image: circleci/node:14-browsers
      - image: scttcper/plex-with-media
    steps:
      - checkout
      - node/install-packages
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: claim-server
          command: npm run claim-server
      - run:
          name: add-media
          command: npm run add-media
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: './reports'
            JEST_JUNIT_OUTPUT_NAME: 'test-results.xml'
      - store_test_results:
          path: ./reports
      - codecov/upload
  cleanup:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npm run test-cleanup
  release:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - cleanup
      - test:
          requires:
            - cleanup
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - test
